spring:
  datasource:
    url: jdbc:mysql://localhost:3306/item_bank?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root  # 加密（生产环境使用），需要配置解密
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver # mysql 8.x要加“cj”
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000 # 配置获取连接等待超时的时间
      validation-query: SELECT 1 # 验证连接
      validation-query-timeout: 2000

  ###Redis
  redis:

    host: 47.115.37.98
    port: 6379
    timeout: 2000ms
    password: 19981020

    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 2
        max-wait: 1000ms

### jwt
jwt:
  ###过期时间
  time: 1800 # (30分钟)
  ###安全密钥
  secret: "itemBankSecret"
  ###token前缀
  prefix: "Bearer "
  ###http头key
  header: "Authorization"

mybatis:
  ### 数据库模型对象
  type-aliases-package: com.item_backend.model.entity
  mapper-locations: mapper/*.xml

logging:
  level:
    root: info
  path: E:/log/item_backend_v1.0


server:
  port: 8080